const brochure = (name: string) => `/images/brochure/${name}`;
const page = (num: number) =>
  `/images/pages/page${String(num).padStart(2, "0")}.jpg`;

export const images = {
  hero: { src: brochure("page01_img01.jpg"), alt: "Kannai Agro Tourism Centre in Gharpi, Maharashtra" },
  about: { src: brochure("page02_img01.jpg"), alt: "Lush green landscapes of Gharpi village" },
  howToReach: { src: brochure("page03_img01.jpg"), alt: "Scenic route to Kannai Agro Tourism" },
  cottage: { src: brochure("page04_img01.jpg"), alt: "The picturesque cottage built with traditional materials" },
  cottageVeranda: { src: brochure("page05_img01.jpg"), alt: "Cottage veranda overlooking the landscape" },
  bedroom: { src: brochure("page06_img01.jpg"), alt: "Spacious master bedroom with organic comfort" },
  bedroomWindows: { src: brochure("page07_img01.jpg"), alt: "Ample windows with breathtaking views" },
  bedroomVeranda: { src: brochure("page07_img03.jpg"), alt: "Spacious veranda with views of wild pasture" },
  digitalDetox: { src: brochure("page08_img01.jpg"), alt: "Peaceful setting for digital detox" },
  washroom: { src: brochure("page09_img01.jpg"), alt: "Clean and well-kept washrooms" },
  restaurant: { src: brochure("page10_img01.jpg"), alt: "Open breezy restaurant serving organic meals" },
  restaurantInterior: { src: brochure("page11_img03.jpg"), alt: "Kitchen restaurant with healthy meals" },
  trails: { src: brochure("page12_img01.jpg"), alt: "Well laid out trails through plantations" },
  flora: { src: brochure("page12_img01.jpg"), alt: "Rich flora and farm fields at Kannai" },
  coconut: { src: brochure("page14_img01.jpg"), alt: "Coconut plantation lining the trails" },
  lemongrass: { src: brochure("page15_img01.jpg"), alt: "Lemongrass plantation and oil extraction" },
  orange: { src: brochure("page16_img01.jpg"), alt: "Orange plantation" },
  pineapple: { src: brochure("page17_img01.jpg"), alt: "Organic pineapple farming" },
  coffee: { src: brochure("page18_img01.jpg"), alt: "Coffee plantation" },
  pepperVanilla: { src: brochure("page19_img02.jpg"), alt: "Black pepper and vanilla plantations" },
  strawberry: { src: brochure("page20_img02.jpg"), alt: "Organic strawberry plantation" },
  fruitsOnGo: { src: brochure("page21_img01.jpg"), alt: "Fresh fruits along the trails" },
  kumkumTree: { src: brochure("page22_img01.jpg"), alt: "Mallotus Philippensis - Kumkum tree" },
  sacredFig: { src: brochure("page23_img01.jpg"), alt: "Sacred fig tree - Ficus Religiosa" },
  landscape: { src: brochure("page24_img01.jpg"), alt: "Ever-changing mesmerising landscape" },
  waterFeatures: { src: brochure("page27_img03.jpg"), alt: "Natural water features on the property" },
  waterfall: { src: brochure("page28_img01.jpg"), alt: "Natural waterfall through scenic trails" },
  fauna: { src: page(30), alt: "Diverse fauna of the region" },
  faunaWildlife: { src: "/images/fauna/wildlife-birds.jpg", alt: "Indian peafowl in a lush forest — wildlife at Kannai" },
  poultry: { src: brochure("page31_img01.jpg"), alt: "Chickens roaming freely on the organic poultry farm" },
  poultryRooster: { src: brochure("page31_img02.jpg"), alt: "Rooster on the organic poultry farm" },
  goats: { src: brochure("page32_img01.jpg"), alt: "Goat farm" },
  cows: { src: brochure("page33_img01.jpg"), alt: "Cows grazing on the organic farm" },
  turtle: { src: brochure("page34_img01.jpg"), alt: "Turtle basking in the sun" },
  solar: { src: page(35), alt: "Solar farm powering the property" },
} as const;

export const galleryImages = {
  stay: [images.cottage, images.bedroom, images.bedroomVeranda, images.washroom],
  dining: [images.restaurant, images.restaurantInterior],
  explore: [images.trails, images.waterFeatures, images.waterfall, images.landscape],
  flora: [
    images.flora,
    images.coconut,
    images.lemongrass,
    images.orange,
    images.pineapple,
    images.coffee,
    images.pepperVanilla,
    images.strawberry,
    images.kumkumTree,
    images.sacredFig,
  ],
  fauna: [images.poultry, images.goats, images.turtle],
} as const;

export const homeSlides = [
  { ...images.cottage, href: "/stay", category: "Stay", caption: "The picturesque cottage" },
  { ...images.bedroom, href: "/stay", category: "Stay", caption: "Master bedroom" },
  { ...images.cottageVeranda, href: "/stay", category: "Stay", caption: "Cottage veranda" },
  { ...images.restaurant, href: "/dining", category: "Dining", caption: "Open-air restaurant" },
  { ...images.restaurantInterior, href: "/dining", category: "Dining", caption: "Organic kitchen" },
  { ...images.trails, href: "/explore", category: "Explore", caption: "Plantation trails" },
  { ...images.waterfall, href: "/explore", category: "Explore", caption: "Natural waterfall" },
  { ...images.waterFeatures, href: "/explore", category: "Explore", caption: "Water features" },
  { ...images.landscape, href: "/explore", category: "Explore", caption: "Western Ghats views" },
  { ...images.coconut, href: "/flora", category: "Flora", caption: "Coconut plantation" },
  { ...images.strawberry, href: "/flora", category: "Flora", caption: "Strawberry fields" },
  { ...images.coffee, href: "/flora", category: "Flora", caption: "Coffee plantation" },
  { ...images.pineapple, href: "/flora", category: "Flora", caption: "Pineapple farming" },
  { ...images.lemongrass, href: "/flora", category: "Flora", caption: "Lemongrass" },
  { ...images.faunaWildlife, href: "/fauna", category: "Fauna", caption: "Peafowl in the forest" },
  { ...images.cows, href: "/fauna", category: "Fauna", caption: "Organic farm" },
  { ...images.goats, href: "/fauna", category: "Fauna", caption: "Goat farm" },
  { ...images.solar, href: "/sustainability", category: "Sustainability", caption: "Solar farm" },
  { ...images.about, href: "/about", category: "About", caption: "Gharpi village" },
] as const;

export const discoverLinks = [
  { href: "/stay", title: "Stay", description: "A picturesque cottage built with traditional materials, powered by green energy.", image: images.cottage },
  { href: "/dining", title: "Dining", description: "Organic vegetarian and non-vegetarian meals slow-cooked on firewood.", image: images.restaurant },
  { href: "/explore", title: "Explore", description: "Trails through plantations and four distinct water features.", image: images.waterfall },
  { href: "/flora", title: "Flora", description: "Coffee, coconut, lemongrass, strawberries, and rare medicinal trees.", image: images.strawberry },
  { href: "/fauna", title: "Fauna", description: "Peacocks, hornbills, organic poultry, and native wildlife.", image: images.faunaWildlife },
  { href: "/sustainability", title: "Sustainability", description: "Solar and hydel energy powering the entire property.", image: images.solar },
] as const;
